export const mockAuthorities = [
  {
    id: 'auth1',
    name: 'Dr. Rajesh Patil',
    role: 'District Disaster Management Officer',
    department: 'DDMA Pune',
    phone: '+91-20-25501001',
    email: 'ddma.pune@gov.in',
    district: 'Pune',
  },
  {
    id: 'auth2',
    name: 'Sunita Sharma',
    role: 'Fire Safety Director',
    department: 'Mumbai Fire Brigade',
    phone: '+91-22-23001010',
    email: 'fire.brigade@mumbai.gov.in',
    district: 'Mumbai',
  },
  {
    id: 'auth3',
    name: 'Amit Deshmukh',
    role: 'NDRF Team Leader',
    department: 'National Disaster Response Force',
    phone: '+91-712-2550200',
    email: 'ndrf.nagpur@gov.in',
    district: 'Nagpur',
  },
  {
    id: 'auth4',
    name: 'Priya Kulkarni',
    role: 'Revenue Officer (Disaster)',
    department: 'Collector Office Pune',
    phone: '+91-20-25501500',
    email: 'revenue.pune@gov.in',
    district: 'Pune',
  },
  {
    id: 'auth5',
    name: 'Vikram Joshi',
    role: 'SDRF Coordinator',
    department: 'State Disaster Response Fund',
    phone: '+91-22-22025000',
    email: 'sdrf.maharashtra@gov.in',
    district: 'Mumbai',
  },
  {
    id: 'auth6',
    name: 'Meena Raut',
    role: 'Medical Officer (Emergency)',
    department: 'District Hospital Nagpur',
    phone: '+91-712-2550300',
    email: 'medical.nagpur@gov.in',
    district: 'Nagpur',
  },
];
