export const mockEvents = [
  {
    id: '1',
    title: 'Earthquake Preparedness Drill',
    type: 'Mock Drill',
    description: 'A comprehensive earthquake simulation drill covering drop-cover-hold techniques, evacuation procedures, and first aid responses for earthquake scenarios.',
    date: '2026-08-25',
    time: '10:00 AM',
    location: 'Community Hall, Sector 12',
    district: 'Pune',
    lat: 18.5204,
    lng: 73.8567,
    status: 'upcoming',
    enrolledCount: 147,
    maxCapacity: 200,
    tags: ['Earthquake', 'Safety'],
  },
  {
    id: '2',
    title: 'Flood Response Workshop',
    type: 'SSP',
    description: 'Interactive workshop on flood preparedness including sandbag techniques, emergency kit preparation, and safe evacuation routes.',
    date: '2026-08-28',
    time: '2:00 PM',
    location: 'District Collector Office',
    district: 'Mumbai',
    lat: 19.076,
    lng: 72.8777,
    status: 'upcoming',
    enrolledCount: 89,
    maxCapacity: 150,
    tags: ['Flood', 'Workshop'],
  },
  {
    id: '3',
    title: 'Fire Safety Certification',
    type: 'CAP',
    description: 'Fire safety training covering fire extinguisher usage, building evacuation plans, and emergency communication protocols.',
    date: '2026-09-01',
    time: '9:00 AM',
    location: 'Fire Station, Main Road',
    district: 'Nagpur',
    lat: 21.1458,
    lng: 79.0882,
    status: 'upcoming',
    enrolledCount: 62,
    maxCapacity: 100,
    tags: ['Fire', 'Certification'],
  },
  {
    id: '4',
    title: 'Cyclone Awareness Camp',
    type: 'Mock Drill',
    description: 'Full-day cyclone preparedness camp with simulation exercises, shelter identification, and emergency supply distribution.',
    date: '2026-09-05',
    time: '8:00 AM',
    location: 'Coastal Community Center',
    district: 'Mumbai',
    lat: 19.0596,
    lng: 72.8295,
    status: 'upcoming',
    enrolledCount: 203,
    maxCapacity: 250,
    tags: ['Cyclone', 'Camp'],
  },
  {
    id: '5',
    title: 'First Aid Training Session',
    type: 'SSP',
    description: 'Basic first aid and CPR training for disaster response volunteers.',
    date: '2026-09-10',
    time: '11:00 AM',
    location: 'Red Cross Building',
    district: 'Pune',
    lat: 18.5309,
    lng: 73.8475,
    status: 'upcoming',
    enrolledCount: 34,
    maxCapacity: 60,
    tags: ['First Aid', 'Training'],
  },
  {
    id: '6',
    title: 'Tsunami Evacuation Drill',
    type: 'Mock Drill',
    description: 'Coastal evacuation drill simulating tsunami warning and safe zone relocation for beachside communities.',
    date: '2026-09-15',
    time: '7:00 AM',
    location: 'Juhu Beach Access Point',
    district: 'Mumbai',
    lat: 19.0948,
    lng: 72.8267,
    status: 'upcoming',
    enrolledCount: 178,
    maxCapacity: 300,
    tags: ['Tsunami', 'Evacuation'],
  },
];
