export const mockAlerts = [
  {
    id: 'a1',
    title: 'Heavy Rainfall Warning',
    message: 'IMD issues red alert for Mumbai district. Expected rainfall 200mm+ in 24 hours. Avoid coastal areas and low-lying regions.',
    severity: 'critical',
    district: 'Mumbai',
    createdAt: '2026-08-19T06:00:00Z',
    expiresAt: '2026-08-21T06:00:00Z',
    active: true,
  },
  {
    id: 'a2',
    title: 'Heatwave Advisory',
    message: 'Temperature expected to exceed 42°C in Nagpur district. Stay hydrated, avoid outdoor activities between 12-4 PM.',
    severity: 'warning',
    district: 'Nagpur',
    createdAt: '2026-08-18T08:00:00Z',
    expiresAt: '2026-08-20T18:00:00Z',
    active: true,
  },
  {
    id: 'a3',
    title: 'Earthquake Tremor Alert',
    message: 'Minor earthquake recorded (magnitude 3.2) near Pune. No damage expected but stay vigilant.',
    severity: 'info',
    district: 'Pune',
    createdAt: '2026-08-17T14:00:00Z',
    expiresAt: '2026-08-18T14:00:00Z',
    active: false,
  },
];

export const mockShelters = [
  {
    id: 's1',
    name: 'Pune Municipal School Shelter',
    distance: '2.3 km',
    occupancy: 45,
    status: 'Available',
    lat: 18.5240,
    lng: 73.8530,
  },
  {
    id: 's2',
    name: 'Sector 12 Community Hall',
    distance: '0.8 km',
    occupancy: 72,
    status: 'Filling',
    lat: 18.5190,
    lng: 73.8590,
  },
  {
    id: 's3',
    name: 'St. Marys High School',
    distance: '3.1 km',
    occupancy: 20,
    status: 'Available',
    lat: 18.5280,
    lng: 73.8500,
  },
  {
    id: 's4',
    name: 'District Sports Complex',
    distance: '4.5 km',
    occupancy: 90,
    status: 'Nearly Full',
    lat: 18.5150,
    lng: 73.8620,
  },
];
