export const mockDisasters = [
  {
    id: 'd1',
    name: 'Maharashtra Floods 2023',
    type: 'Flood',
    date: '2023-07-15',
    district: 'Kokana',
    casualties: 42,
    displaced: 12500,
    damageEstimate: '₹850 Cr',
    summary: 'Severe flooding caused by heavy monsoon rains led to widespread displacement and infrastructure damage across western Maharashtra.',
  },
  {
    id: 'd2',
    name: 'Latur Earthquake 2024',
    type: 'Earthquake',
    date: '2024-03-22',
    district: 'Latur',
    casualties: 8,
    displaced: 3200,
    damageEstimate: '₹220 Cr',
    summary: 'A 5.4 magnitude earthquake struck Latur district, causing structural damage to older buildings.',
  },
  {
    id: 'd3',
    name: 'Cyclone Tauktae Impact',
    type: 'Cyclone',
    date: '2024-05-18',
    district: 'Mumbai',
    casualties: 3,
    displaced: 8500,
    damageEstimate: '₹1200 Cr',
    summary: 'Severe cyclone brought wind speeds of 150km/h and heavy rainfall to the Mumbai coast.',
  },
  {
    id: 'd4',
    name: 'Nagpur Wildfires',
    type: 'Fire',
    date: '2025-04-10',
    district: 'Nagpur',
    casualties: 0,
    displaced: 1200,
    damageEstimate: '₹45 Cr',
    summary: 'Forest fires in the Vidarbha region threatened residential areas on the outskirts of Nagpur.',
  },
  {
    id: 'd5',
    name: 'Konkan Landslides',
    type: 'Landslide',
    date: '2025-07-22',
    district: 'Raigad',
    casualties: 15,
    displaced: 4800,
    damageEstimate: '₹380 Cr',
    summary: 'Torrential rainfall triggered multiple landslides in hilly terrain, cutting off several villages.',
  },
  {
    id: 'd6',
    name: 'Pune Industrial Accident',
    type: 'Industrial',
    date: '2025-11-05',
    district: 'Pune',
    casualties: 5,
    displaced: 2000,
    damageEstimate: '₹150 Cr',
    summary: 'Chemical leak at an industrial estate prompted mass evacuation of surrounding neighborhoods.',
  },
];
